
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package arbol_graficado;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int como = 37;
  public static final int abre_parentesis = 25;
  public static final int frase = 11;
  public static final int mayor_o_igual = 29;
  public static final int imprimir = 64;
  public static final int con_parametros = 60;
  public static final int mod = 24;
  public static final int hasta = 50;
  public static final int es_diferente = 32;
  public static final int cierra_pregunta = 44;
  public static final int hasta_que = 56;
  public static final int coma = 40;
  public static final int entonces = 46;
  public static final int punto_y_coma = 39;
  public static final int fin_funcion = 62;
  public static final int inicio = 2;
  public static final int guion = 7;
  public static final int caracter = 15;
  public static final int repetir = 55;
  public static final int fin_metodo = 59;
  public static final int dividido = 20;
  public static final int si = 41;
  public static final int mientras = 53;
  public static final int bulean = 12;
  public static final int con_incremental = 66;
  public static final int es_igual = 31;
  public static final int fin_si = 48;
  public static final int abre_pregunta = 43;
  public static final int menor_o_igual = 30;
  public static final int numero = 8;
  public static final int finall = 3;
  public static final int menos = 18;
  public static final int menor = 28;
  public static final int fin_mientras = 54;
  public static final int EOF = 0;
  public static final int mas = 17;
  public static final int para = 49;
  public static final int verdadero = 13;
  public static final int fin_para = 51;
  public static final int error = 1;
  public static final int mayor = 27;
  public static final int metodo = 58;
  public static final int or = 33;
  public static final int por = 19;
  public static final int cierra_corchete = 22;
  public static final int funcion = 61;
  public static final int imprimir_nl = 65;
  public static final int potencia = 23;
  public static final int id = 5;
  public static final int falso = 14;
  public static final int fin_segun = 47;
  public static final int segun = 67;
  public static final int hacer = 52;
  public static final int variable = 6;
  public static final int ingresar = 36;
  public static final int con_valor = 38;
  public static final int de_lo_contrario = 45;
  public static final int not = 35;
  public static final int and = 34;
  public static final int retornar = 57;
  public static final int abre_corchete = 21;
  public static final int o_si = 42;
  public static final int flechita = 4;
  public static final int frasecita = 16;
  public static final int ejecutar = 63;
  public static final int cierra_parentesis = 26;
  public static final int cadena = 10;
  public static final int number = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "inicio",
  "finall",
  "flechita",
  "id",
  "variable",
  "guion",
  "numero",
  "number",
  "cadena",
  "frase",
  "bulean",
  "verdadero",
  "falso",
  "caracter",
  "frasecita",
  "mas",
  "menos",
  "por",
  "dividido",
  "abre_corchete",
  "cierra_corchete",
  "potencia",
  "mod",
  "abre_parentesis",
  "cierra_parentesis",
  "mayor",
  "menor",
  "mayor_o_igual",
  "menor_o_igual",
  "es_igual",
  "es_diferente",
  "or",
  "and",
  "not",
  "ingresar",
  "como",
  "con_valor",
  "punto_y_coma",
  "coma",
  "si",
  "o_si",
  "abre_pregunta",
  "cierra_pregunta",
  "de_lo_contrario",
  "entonces",
  "fin_segun",
  "fin_si",
  "para",
  "hasta",
  "fin_para",
  "hacer",
  "mientras",
  "fin_mientras",
  "repetir",
  "hasta_que",
  "retornar",
  "metodo",
  "fin_metodo",
  "con_parametros",
  "funcion",
  "fin_funcion",
  "ejecutar",
  "imprimir",
  "imprimir_nl",
  "con_incremental",
  "segun"
  };
}

